version: '3.4'

services:
  devops.products.reviews.rest.api:
    image: ${DOCKER_REGISTRY-}devopsproductsreviewsrestapi
    container_name: reviews
    build:
      context: .
      dockerfile: DevOps.Products.Reviews.REST.API/Dockerfile

  devops.products.products.rest.api:
    image: ${DOCKER_REGISTRY-}devopsproductsproductsrestapi
    container_name: products
    build:
      context: .
      dockerfile: DevOps.Products.Products.REST.API/Dockerfile

  devops.products.website:
    image: ${DOCKER_REGISTRY-}devopsproductswebsite
    container_name: website
    build:
      context: .
      dockerfile: DevOps.Products.Website/Dockerfile
    links:
      - "devops.products.products.rest.api:products"
      - "devops.products.reviews.rest.api:reviews"
    depends_on:
      - devops.products.products.rest.api
      - devops.products.reviews.rest.api
